Transportsimple/Quora_project/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path("signup/", views.register, name="signup"),
    path('edit/', views.edit, name='edit'),

    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),

    #change password urls
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #reset password
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
]

Transportsimple/Quora_project/core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.home,name="home"),
    path('add_question',views.create_question, name="add_question"),
    path('question/<int:pk>/', views.question_detail, name="question_detail"),
    path('answer/like/<int:pk>/', views.like_answer, name='like_answer'),
]

Transportsimple/Quora_project/quora/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls",namespace='account')),
    path("", include("core.urls")),
]

Transportsimple/Quora_project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Quora</title>
    </head>
  <body>

        <a  href="#">Quora</a><br>

            <a  aria-current="page" href="{% url 'home' %}">Home</a><br>
            <a  href="{% url 'add_question' %}">Add Question</a><br>


            {% if request.user.is_authenticated %}
            <a  href="#">Hi ,{{ request.user.username }}</a><br>
            {% if request.user.is_superuser %}
            <a  href="{% url 'admin:index' %}">Admin Panel</a><br>
             {% endif %}
            <a  href="{% url 'account:logout' %}">Logout</a><br>
            {% else %}
            <a  href="{% url 'account:signup' %}">Sign Up</a><br>
            <a  href="{% url 'account:login' %}">Login</a>
            {% endif %}
            
           
              

    {% block content %}
    
    
    {% endblock content %}
      </body>
</html>